### ISSUE TITLE
Trying to build with num-traits 0.1.37 fails on num-complex 0.1.39

### ISSUE THREAD

**Issue by vvanders** [rust-num/num#322]
Seeing this with a Cargo.lock that's pinned num-traits to 0.1.37:

```
   Compiling num-complex v0.1.39
error[E0432]: unresolved import `traits::NumAssign`
   --> <omitted>\.cargo\registry\src\github.com-1ecc6299db9ec823\num-complex-0.1.39\src\lib.rs:524:9
    |
524 |     use traits::NumAssign;
    |         ^^^^^^^^^^^^^^^^^ no `NumAssign` in the root
````

My understanding with semver is that 0.1.40(which succeeds) and 0.1.37 should be API compatible.

**Comment by cuviper** [comment]
API-compatible can still add new things, but I should have bumped up num-complex's dependency on num-traits for using the new `NumAssign`. I'll push an update.

If for some reason you can't use the newer num-traits, then you'll have to lock an older num-complex too.

**Comment by vvanders** [comment]
Yeah, I just cargo update'd to the newest versions. Just wanted to throw it out there in case anyone else sees a similar issue.

**Comment by cuviper** [comment]
Thanks, num-complex-0.1.40 should fix this.
